//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonstrationExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWorkshops
    {
        public int ProductWorkshopId { get; set; }
        public int ProductID { get; set; }
        public int WorkshopID { get; set; }
        public double BuildTime { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Workshops Workshops { get; set; }
    }
}
