//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonstrationExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workshops()
        {
            this.ProductWorkshops = new HashSet<ProductWorkshops>();
        }
    
        public int WorshopID { get; set; }
        public string WorkshopName { get; set; }
        public string WorkshopType { get; set; }
        public int WorkersAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWorkshops> ProductWorkshops { get; set; }
    }
}
